<?php
function a($t,$w){$c="";switch($w){case'red':$c="\033[31m";break;case'green':$c="\033[32m";break;case'yellow':$c="\033[33m";break;case'blue':$c="\033[34m";break;case'magenta':$c="\033[35m";break;case'cyan':$c="\033[36m";break;case'white':$c="\033[37m";break;default:$c="";}return$c.$t."\033[0m";}
function b($d=3){$l=['|','/','-','\\'];$s=time();while(time()-$s<$d){foreach($l as $k){echo"\r".a("Generating image $k",'yellow');usleep(200000);}}echo"\r".a("Finished generating image!",'green').PHP_EOL;}
function c($d=2){$l=['|','/','-','\\'];$s=time();while(time()-$s<$d){foreach($l as $k){echo"\r".a("Saving file $k",'yellow');usleep(200000);}}echo"\r".a("File saved successfully!",'green').PHP_EOL;}
function d($p,$m,$s){$k="YOUR_API_KEY";$url="https://api.neoxr.eu/api/genimg?prompt=".urlencode($p)."&model=$m&sampler=$s&apikey=$k";$ch=curl_init();curl_setopt($ch,CURLOPT_URL,$url);curl_setopt($ch,CURLOPT_RETURNTRANSFER,true);$r=curl_exec($ch);curl_close($ch);if(!$r){return['status'=>false,'msg'=>'Cannot connect to API'];}$res=json_decode($r,true);if(json_last_error()!==JSON_ERROR_NONE||!$res['status']){return['status'=>false,'msg'=>$res['msg']??'Failed to parse JSON'];}return$res;}
function e($url,$path){$data=@file_get_contents($url);if($data===false){return false;}file_put_contents($path,$data);return true;}
function f(){if(file_exists('DataGenIMG-Model.json')){$json=file_get_contents('DataGenIMG-Model.json');$data=json_decode($json,true);if(is_array($data)&&isset($data['models'])){echo a("Available Models:\n",'cyan');foreach($data['models'] as $model){if(isset($model['model_id'])&&isset($model['name'])){echo a("Model Name: ",'blue').a($model['name'],'white')."\n";echo a("Model ID: ",'red').a($model['model_id'],'white')."\n";echo a("IDS: ",'yellow').a($model['ids'],'white')."\n";echo"\n";}else{echo a("Incomplete model data.\n",'red');}}}else{echo a("Failed to read model JSON file or invalid format.\n",'red');exit;}}else{echo a("Model JSON file not found.\n",'red');exit;}}
function g($j){echo"\n".a("Image Results:\n",'cyan');echo a("File Name: ",'blue').$j['nama_file']."\n";echo a("Storage Location: ",'green').$j['direktori']."\n";echo a("Image Link: ",'yellow').$j['link_gambar']."\n";echo a("Model: ",'magenta').$j['model']."\n";echo"\n".a("Press Enter to continue...",'white');fgets(STDIN);}
function h($m){if(file_exists('DataGenIMG-Model.json')){$j=file_get_contents('DataGenIMG-Model.json');$data=json_decode($j,true);if(is_array($data)&&isset($data['models'])){foreach($data['models'] as $model){if(isset($model['model_id'])&&$model['model_id']==$m){return true;}}}}return false;}
function i($p,$m,$s){echo a("Starting image retrieval process...\n",'blue');b();$response=d($p,$m,$s);if($response['status']){$modelName=$response['data']['options']['sd_model_checkpoint'];$urlGambar=$response['data']['url'];$dir="Result/GenIMG/".str_replace(' ','_',$modelName);if(!is_dir($dir)){mkdir($dir,0777,true);} $fileName=str_replace(' ','_',$p).'.jpg';$path=$dir.'/'.$fileName;$counter=1;while(file_exists($path)){$fileName=str_replace(' ','_',$p).'-'.$counter.'.jpg';$path=$dir.'/'.$fileName;$counter++;}if(e($urlGambar,$path)){c();$dataJson=['nama_file'=>$fileName,'direktori'=>$dir,'link_gambar'=>$urlGambar,'model'=>$modelName];if(file_exists('DataGenIMG.json')){$data=json_decode(file_get_contents('DataGenIMG.json'),true);}else{$data=[];} $data[]=$dataJson;file_put_contents('DataGenIMG.json',json_encode($data,JSON_PRETTY_PRINT));g($dataJson);}else{echo a("Failed to save image from URL: $urlGambar\n",'red');}}else{echo a("Error: ".$response['msg']."\n",'red');}}
function j(){echo a("Welcome to the Text-to-Image Generator program!\n\n",'blue');do{echo a("Enter the text to convert to image: ",'green');$prompt=trim(fgets(STDIN));if(strtolower($prompt)==='exit'){echo a("Exiting the program. Thank you!\n",'blue');exit;}do{echo a("Enter model ID: ",'green');$model=trim(fgets(STDIN));if(!h($model)){echo a("Error: Model ID Not Found\n",'red');echo a("Type: \"zora help\" to display available models.\n",'green');}}while(!h($model));echo a("Choose sampler (default: 4): ",'green');$sampler=trim(fgets(STDIN));if(strtolower($sampler)==='exit'){echo a("Exiting the program. Thank you!\n",'blue');exit;}if(!is_numeric($sampler)){$sampler=4;}i($prompt,$model,$sampler);echo a("Do you want to generate another image? (y/n): ",'yellow');$ulang=trim(fgets(STDIN));if(empty($ulang)){$ulang='y';}if(strtolower($ulang)!=='y'){echo a("Exiting the program. Thank you!\n",'blue');break;}}while(true);}
j();
?>
